---
# First ensure no other apt processes are running
- name: Wait for apt locks
  shell: while fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do sleep 1; done
  when: ansible_os_family == "Debian"

- name: Clean up existing Docker repository configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/keyrings/docker.asc
    - /etc/apt/trusted.gpg.d/docker.gpg
    - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
  when: ansible_os_family == "Debian"

- name: Update package cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  register: apt_update
  retries: 5
  delay: 10
  until: apt_update is success

- name: Update package cache (RHEL)
  dnf:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install required packages (Debian/Ubuntu)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
      - python3-dev
      - python3-yaml
      - python3-setuptools
      - python3-requests
      - python3-docker
      - python3-urllib3
      - build-essential
      - git
    state: present
  when: ansible_os_family == "Debian"
  register: apt_install
  retries: 5
  delay: 10
  until: apt_install is success

- name: Install required packages (RHEL)
  dnf:
    name:
      - ca-certificates
      - curl
      - dnf-plugins-core
      - python3
      - python3-pip
      - python3-devel
      - python3-pyyaml
      - python3-setuptools
      - python3-requests
      - python3-docker
      - python3-urllib3
      - gcc
      - gcc-c++
      - make
      - git
    state: present
  when: ansible_os_family == "RedHat"

# Python packages for Ansible Docker modules are now installed via system package manager above
# This avoids PEP 668 "externally-managed-environment" issues on newer Python versions

#- name: Ensure system is updated (Debian/Ubuntu)
#  apt:
#    upgrade: full
#    update_cache: yes
#  when: ansible_os_family == "Debian"
#  register: apt_upgrade
#  retries: 5
#  delay: 10
#  until: apt_upgrade is success

#- name: Ensure system is updated (RHEL)
#  dnf:
#    name: "*"
#    state: latest
#  when: ansible_os_family == "RedHat"