namespace: "ratio1"
name: "r1setup"
version: "1.1.16"
readme: "README.md"
authors:
  - Andrei Damian <andrei.damian@me.com>
  - Vitalii Toderian <vitalii.tdev@gmail.com>
description: "Multi Node Launcher application"
license:
  - "MIT"
tags:
  - application
  - deployment
  - launcher
  - ratio1
repository: "https://github.com/Ratio1/r1setup"
documentation: "http://docs.example.com"
homepage: "http://example.com"
issues: "https://github.com/yourusername/r1setup/issues"
