---
# Skip this role entirely if skip_gpu is set to true
- name: Skip NVIDIA drivers setup when skip_gpu is true
  debug:
    msg: "NVIDIA drivers setup skipped due to skip_gpu=true configuration"
  when: skip_gpu is defined and skip_gpu
  tags: never

# First, detect OS family
- name: Detect OS family
  set_fact:
    is_ubuntu: ansible_distribution == "Ubuntu"
    is_debian: ansible_distribution == "Debian"
    is_rhel: ansible_os_family == "RedHat"
  when: skip_gpu is not defined or not skip_gpu

- name: Check for NVIDIA GPU
  shell: "lspci | grep -i nvidia"
  register: nvidia_check
  ignore_errors: yes
  changed_when: false
  when: skip_gpu is not defined or not skip_gpu

- name: Skip message if no NVIDIA GPU found
  debug:
    msg: "No NVIDIA GPU detected. Skipping driver installation."
  when: 
    - (skip_gpu is not defined or not skip_gpu)
    - nvidia_check.rc != 0

- block:
    # Ubuntu/Debian specific tasks
    - name: Ubuntu/Debian - Add NVIDIA repository
      block:
        - name: Add NVIDIA repository
          apt_repository:
            repo: ppa:graphics-drivers/ppa
            state: present
      when: is_ubuntu or is_debian

    - name: Ubuntu/Debian - Install NVIDIA drivers
      apt:
        name: 
          - nvidia-driver-{{ nvidia_driver_version }}
        state: present
        update_cache: yes
      when: is_ubuntu or is_debian

    - name: Check if nvidia-container-toolkit is available in repositories
      shell: "apt-cache search nvidia-container-toolkit | grep '^nvidia-container-toolkit '"
      register: nvidia_toolkit_available
      ignore_errors: true
      changed_when: false

    - name: Setup NVIDIA Container Toolkit repository if not available
      block:
        - name: Download NVIDIA container toolkit repository setup script
          get_url:
            url: https://nvidia.github.io/libnvidia-container/gpgkey
            dest: /tmp/nvidia-container-toolkit-keyring.gpg
            mode: '0644'

        - name: Install GPG key
          shell: |
            gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia-container-toolkit-keyring.gpg
          args:
            creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

        - name: Get distribution information
          set_fact:
            distro_id: "{{ ansible_distribution | lower }}"
            distro_version: "{{ ansible_distribution_version }}"

        - name: Add NVIDIA Container Toolkit repository
          shell: |
            curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
              sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
              tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          args:
            creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

        - name: Update apt cache after adding repository
          apt:
            update_cache: yes
      when: nvidia_toolkit_available.rc != 0

    - name: Ubuntu/Debian - Install NVIDIA Docker packages
      apt:
        name:
          - nvidia-container-toolkit
        state: present
        update_cache: yes
      when: is_ubuntu or is_debian
      register: nvidia_toolkit_install
      retries: 3
      delay: 5
      until: nvidia_toolkit_install is success

    - name: Configure Docker to use NVIDIA runtime
      shell: nvidia-ctk runtime configure --runtime=docker
      when: nvidia_toolkit_install is success
      register: nvidia_runtime_config
      ignore_errors: true

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
      when: 
        - nvidia_toolkit_install is success
        - nvidia_runtime_config.rc == 0

# Running this in nvidia_gpu role
#    # Install nvtop for monitoring NVIDIA GPUs
#    - name: Ubuntu/Debian - Install nvtop
#      apt:
#        name: nvtop
#        state: present
#        update_cache: yes
#      when: is_ubuntu or is_debian
#
#    # RHEL specific tasks
#    - name: RHEL - Enable EPEL repository
#      yum:
#        name: epel-release
#        state: present
#      when: is_rhel
#
#    - name: RHEL - Install nvtop
#      yum:
#        name: nvtop
#        state: present
#      when: is_rhel
#
#    - name: RHEL - Add NVIDIA repository
#      yum_repository:
#        name: nvidia-driver
#        description: NVIDIA Driver Repository
#        baseurl: https://download.nvidia.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch
#        gpgkey: https://download.nvidia.com/linux/{{ ansible_distribution | lower }}/nvidia-driver-local-repo-{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.pub
#        gpgcheck: yes
#        enabled: yes
#      when: is_rhel

  # Only run this block if NVIDIA GPU is detected
  when: 
    - (skip_gpu is not defined or not skip_gpu)
    - nvidia_check.rc == 0 